name: CI&CD Build Production
on:
  push:
    branches:
      - main
jobs:
  build:
    name: CI&CD Build
    runs-on: ubuntu-latest
    env:
      LAMBDA_FUNCTION_NAME: 'watermelonwale_bot'
      S3_BUCKET: 'watermelonwale'
      AWS_REGION_DEFAULT: 'eu-north-1'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20.12.2
      - run: npm ci
      - run: npm run build
      - name: Set lambda name
        run: echo ${{ env.LAMBDA_FUNCTION_NAME }}-`git rev-parse --short HEAD`-`date +%s` > meta.log && cat meta.log
      - name: Archiving files
        run: cd dist/ && zip -r "$(cat ../meta.log)".zip * .env
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_LAMBDA }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_LAMBDA }}
          aws-region: ${{ env.AWS_REGION_DEFAULT }}
      - name: Copy to S3
        run: cd dist/ && aws s3 cp "$(cat ../meta.log)".zip s3://${{ env.S3_BUCKET }}/"$(cat ../meta.log)".zip
      - name: Update lambda
        run: aws lambda update-function-code --function-name "${{ env.LAMBDA_FUNCTION_NAME }}" --s3-bucket "${{ env.S3_BUCKET }}" --s3-key "$(cat meta.log)".zip